'use server';

/**
 * @fileOverview This file defines a Genkit flow for refining prompts using an AI council with different prompting techniques.
 *
 * - refinePromptWithAICouncil - A function that refines a user-provided prompt using an AI council.
 * - RefinePromptWithAICouncilInput - The input type for the refinePromptWithAICouncil function.
 * - RefinePromptWithAICouncilOutput - The return type for the refinePromptWithAICouncil function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefinePromptWithAICouncilInputSchema = z.object({
  prompt: z.string().describe('The prompt to be refined.'),
  promptType: z
    .enum([
      'Zero-shot',
      'Few-shot',
      'Chain-of-thought',
      'Tree-of-thoughts',
      'Role / persona',
      'Prompt chaining',
      'ReAct',
      'Meta / reflection',
    ])
    .describe(
      'The prompting technique to be applied by the AI council for refinement.'
    ),
});
export type RefinePromptWithAICouncilInput = z.infer<typeof RefinePromptWithAICouncilInputSchema>;

const RefinePromptWithAICouncilOutputSchema = z.object({
  refinedPrompt: z.string().describe('The refined prompt generated by the AI council.'),
});
export type RefinePromptWithAICouncilOutput = z.infer<typeof RefinePromptWithAICouncilOutputSchema>;

export async function refinePromptWithAICouncil(
  input: RefinePromptWithAICouncilInput
): Promise<RefinePromptWithAICouncilOutput> {
  return refinePromptWithAICouncilFlow(input);
}

const refinePromptWithAICouncilPrompt = ai.definePrompt({
  name: 'refinePromptWithAICouncilPrompt',
  input: {schema: RefinePromptWithAICouncilInputSchema},
  output: {schema: RefinePromptWithAICouncilOutputSchema},
  prompt: `You are a council of expert prompt engineers. Your goal is to refine the user-provided prompt using the specified prompting technique, which is "{{promptType}}".

  Here are the prompting techniques and their main ideas:
  - Zero-shot: Just instructions, no examples
  - Few-shot: Add a few examples
  - Chain-of-thought: Show step-by-step reasoning
  - Tree-of-thoughts: Explore multiple reasoning branches
  - Role / persona: “Act as X” role control
  - Prompt chaining: Multi-prompt pipelines
  - ReAct: Interleave reasoning and tool use
  - Meta / reflection: Model reasons about its own process

  Based on the prompt type "{{promptType}}", refine the following prompt to get better results:
  """
  {{prompt}}
  """

  Return the refined prompt.
`,
});

const refinePromptWithAICouncilFlow = ai.defineFlow(
  {
    name: 'refinePromptWithAICouncilFlow',
    inputSchema: RefinePromptWithAICouncilInputSchema,
    outputSchema: RefinePromptWithAICouncilOutputSchema,
  },
  async input => {
    const {output} = await refinePromptWithAICouncilPrompt(input);
    return output!;
  }
);
